AeroMAPS/AeroMAPS

aeromaps/core/models.py, aeromaps/gui/graphical_user_interface.py, aeromaps/models/air_transport/aircraft_fleet_and_operations/fleet/aircraft_efficiency.py, aeromaps/models/air_transport/aircraft_fleet_and_operations/fleet/fleet_model.py
This PR aims at integrating updates for the fleet model:
- The computation now starts from an empty dataframe to avoid bugs when running several computations
- The freight model is now common to the simple or complex fleet efficiency models
=> Update fleet model

aeromaps/gui/graphical_user_interface.py
This PR resolves #5 by correcting the file path for the data download.
=> Corrected file path for data download

CHANGELOG.md
https://github.com/AeroMAPS/AeroMAPS/releases/tag/untagged-88e615e6d0614b15b42a
=> Release 0.1.1-beta

CHANGELOG.md
https://github.com/AeroMAPS/AeroMAPS/releases/tag/untagged-9e2187023b973453feaf
=> Release 0.2.0-beta

aeromaps/gui/graphical_user_interface.py, aeromaps/gui/plots.py, aeromaps/plots/climate.py, aeromaps/plots/main.py, aeromaps/plots/sustainability_assessment.py
Improved main CO2 emissions figures
New sustainability assesment graph
Minor improvements
=> Improve figures

aeromaps/core/process.py
This PR resolves #11 by stopping from an empty Dataframe at each run. Also, some refactoring was made for more clarity and efficiency in data handling.
=> Correction of multiple run issue

aeromaps/core/process.py, aeromaps/gui/graphical_user_interface.py
This PR fixes the update of the data tab which remained with initial values.
=> Fix data tab update

CHANGELOG.md
https://github.com/AeroMAPS/AeroMAPS/releases/tag/untagged-9a6bb15480522b399f38
=> Release 0.3.1-beta

.github/workflows/build_release.yml, pyproject.toml
This PR aims at updating the release workflow to benefit from poetry dynamic versioning.
=> New release process

CHANGELOG.md
https://github.com/AeroMAPS/AeroMAPS/releases/tag/untagged-e6763b238bf8079d3237
=> Release 0.4.0-beta

docs/books/citations.md, docs/books/documentation_impacts.md, docs/references.bib
Added cost models documentation to books.
=> Cost documentation

aeromaps/models/impacts/costs/energy/liquid_hydrogen.py, aeromaps/models/impacts/costs/energy/power_to_liquid.py, aeromaps/plots/costs.py
-Bug correction: hydrogen and power to liquid computation: cost scaler nan handling
-Warning correction: canvas layout commented out
=> Correction of hydrogen expenses computation bug

aeromaps/models/air_transport/aircraft_fleet_and_operations/fleet/aircraft_efficiency.py, aeromaps/models/impacts/costs/operations/average_ops_cost.py, aeromaps/notebooks/examples_joas_application.ipynb, docs/books/examples_joas_application.ipynb
Minor correction for JOAS application
=> JOAS correction

CHANGELOG.md
https://github.com/AeroMAPS/AeroMAPS/releases/tag/untagged-24ddb379fdf93a22d372
=> Release 0.4.1-beta

CHANGELOG.md
https://github.com/AeroMAPS/AeroMAPS/releases/tag/untagged-af6fdf116a41c29a1d90
=> Release 0.4.2-beta

CHANGELOG.md
https://github.com/AeroMAPS/AeroMAPS/releases/tag/untagged-bc598c3d31ec3de5bcf1
=> Release 0.5.0-beta

CHANGELOG.md
https://github.com/AeroMAPS/AeroMAPS/releases/tag/untagged-721c3e072f91aa8708f8
=> Release v0.6.0-beta

CHANGELOG.md
https://github.com/AeroMAPS/AeroMAPS/releases/tag/untagged-c64c2d86815bc3d1aa1d
=> Release v0.6.1-beta

CHANGELOG.md
https://github.com/AeroMAPS/AeroMAPS/releases/tag/untagged-e9ba99be37ba7c95f933
=> Release v0.6.2-beta

CHANGELOG.md
https://github.com/AeroMAPS/AeroMAPS/releases/tag/untagged-8c7c9ee72fd7859fac35
=> Release v0.7.0-beta

CHANGELOG.md, pyproject.toml
https://github.com/AeroMAPS/AeroMAPS/releases/tag/untagged-203cd00301d0a55a6ff8
=> Release 0.7.1-beta

CHANGELOG.md, README.md, pyproject.toml
https://github.com/AeroMAPS/AeroMAPS/releases/tag/untagged-14ef433feb36a8f5e388
=> Release 0.8.0-beta

aeromaps/core/process.py, aeromaps/notebooks/publications/tsas_2025/examples_tsas_application.ipynb
The bug was due to higher vector sizes for climate input data
=> Bug fix for running a reduced number of models focusing on climate

aeromaps/models/impacts/emissions/co2_emissions.py
This simple model relies on the direct use of energy consumption.
=> Add a simple model for estimating CO2 emissions

CHANGELOG.md, pyproject.toml
https://github.com/AeroMAPS/AeroMAPS/releases/edit/untagged-07f8724c8034064ca861
=> Release v0.8.1-beta

CHANGELOG.md
https://github.com/AeroMAPS/AeroMAPS/releases/tag/untagged-d5dbc8cb0b7ffcdf1ccc
=> Release 0.8.2-beta

pyproject.toml
This PR (re)-introduces the poetry dynamic versioning mechanism as it is used in the release workflow.
=> Corrected poetry dynamic versioning

CHANGELOG.md, pyproject.toml
https://github.com/AeroMAPS/AeroMAPS/releases/tag/untagged-0a6e047c85b99283a5b8
=> Release 0.8.3-beta
